---

- name: Apply various sysctl tweaks
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/99-sysctl.conf
  with_items:
    - { name: 'vm.swappiness', value: 1 }
    - { name: 'net.core.rmem_max', value: 16777216 }
    - { name: 'net.core.wmem_max', value: 16777216 }
    - { name: 'net.ipv4.ip_local_port_range', value: '1024 65023' }
    - { name: 'net.ipv4.tcp_fin_timeout', value: 30 }
    - { name: 'net.core.netdev_max_backlog', value: 10000 }
    - { name: 'net.ipv4.tcp_max_syn_backlog', value: 2048 }
    - { name: 'net.ipv4.tcp_synack_retries', value: 3 }
    - { name: 'net.ipv4.tcp_syncookies', value: 1 }
    - { name: 'net.ipv4.conf.all.rp_filter', value: 1}
    - { name: 'net.core.somaxconn', value: 60000 }
    - { name: 'net.ipv4.tcp_max_tw_buckets', value: 1440000 }
    - { name: 'net.ipv4.tcp_tw_reuse', value: 1 }
    - { name: 'net.ipv4.tcp_max_orphans', value: 262144 }
    - { name: 'fs.file-max', value: 2097152 }
    - { name: 'vm.dirty_ratio', value: 60 }
    - { name: 'vm.dirty_background_ratio', value: 2 }

- name: Apply sysctl changes
  shell: sysctl --system
  changed_when: False

